#!/usr/bin/env bash
# Generate docs/WALKTHROUGH.md by running hq examples
# This ensures documentation stays in sync with actual behavior

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
HQ="$ROOT_DIR/hq"
OUTPUT="$ROOT_DIR/docs/WALKTHROUGH.md"

# Build hq if needed
if [[ ! -x "$HQ" ]]; then
    echo "Building hq..."
    (cd "$ROOT_DIR" && go build -o hq ./cmd/hq/)
fi

# Create docs directory
mkdir -p "$ROOT_DIR/docs"

# Helper to run an example and capture output
run_example() {
    local cmd="$1"
    # Replace full path with just 'hq' for display
    local display_cmd="${cmd//$HQ/hq}"
    echo '```bash'
    echo "$ $display_cmd"
    eval "$cmd" 2>&1 || true
    echo '```'
    echo
}

# Generate the walkthrough
cat > "$OUTPUT" << 'HEADER'
# hq Walkthrough

> **Note**: This file is auto-generated by `scripts/generate_walkthrough.sh`.
> Do not edit manually - run the script to regenerate.

hq is a lightweight command-line HUML processor with jq-compatible syntax.
It reads JSON, YAML, or HUML input and outputs proper HUML format by default.

## Table of Contents

- [Installation](#installation)
- [Basic Usage](#basic-usage)
- [Identity and Field Access](#identity-and-field-access)
- [Array Operations](#array-operations)
- [Pipe and Filters](#pipe-and-filters)
- [Operators](#operators)
- [Built-in Functions](#built-in-functions)
- [Variables and Binding](#variables-and-binding)
- [Reduce](#reduce)
- [Dynamic Index Access](#dynamic-index-access)
- [Conditionals](#conditionals)
- [Error Handling](#error-handling)
- [String Interpolation](#string-interpolation)
- [Regex](#regex)
- [Recursive Descent](#recursive-descent)
- [Path Operations](#path-operations)
- [Assignment Operators](#assignment-operators)
- [Object Transforms](#object-transforms)
- [Output Formats](#output-formats)
- [Real-World Examples](#real-world-examples)

## Installation

```bash
# Build from source
go build -o hq ./cmd/hq/

# Or install
go install github.com/huml-lang/hq/cmd/hq@latest
```

## Basic Usage

```bash
# Show help
hq --help

# Process JSON input
echo '{"name": "Alice"}' | hq '.'

# Process with null input (for calculations)
hq -n '1 + 2 + 3'

# Output as JSON instead of HUML
echo '{"name": "Alice"}' | hq -o json '.'
```

## Identity and Field Access

The identity operator `.` returns the input unchanged.
Field access uses `.fieldname` syntax.

HEADER

# Add live examples
{
    echo "### Identity"
    echo
    run_example "echo '{\"name\": \"Alice\", \"age\": 30}' | $HQ '.'"

    echo "### Field Access"
    echo
    run_example "echo '{\"name\": \"Alice\", \"age\": 30}' | $HQ '.name'"
    run_example "echo '{\"name\": \"Alice\", \"age\": 30}' | $HQ '.age'"

    echo "### Bracket Notation"
    echo
    echo "Use bracket notation for keys with special characters:"
    echo
    run_example "echo '{\"first name\": \"Alice\"}' | $HQ '.[\"first name\"]'"

    echo "## Array Operations"
    echo
    echo "### Indexing"
    echo
    run_example "echo '[\"a\", \"b\", \"c\", \"d\", \"e\"]' | $HQ '.[0]'"
    run_example "echo '[\"a\", \"b\", \"c\", \"d\", \"e\"]' | $HQ '.[2]'"
    run_example "echo '[\"a\", \"b\", \"c\", \"d\", \"e\"]' | $HQ '.[-1]'"

    echo "### Slicing"
    echo
    run_example "echo '[\"a\", \"b\", \"c\", \"d\", \"e\"]' | $HQ '.[1:4]'"
    run_example "echo '[\"a\", \"b\", \"c\", \"d\", \"e\"]' | $HQ '.[:3]'"
    run_example "echo '[\"a\", \"b\", \"c\", \"d\", \"e\"]' | $HQ '.[-2:]'"

    echo "### Iterator"
    echo
    echo "The iterator \`.[]\ expands arrays into multiple outputs:"
    echo
    run_example "echo '[1, 2, 3]' | $HQ '.[]'"

    echo "For objects, it returns all values:"
    echo
    run_example "echo '{\"a\": 1, \"b\": 2, \"c\": 3}' | $HQ '.[]'"

    echo "## Pipe and Filters"
    echo
    echo "### Pipe Operator"
    echo
    echo "Chain operations with \`|\`:"
    echo
    run_example "echo '[1, 2, 3, 4, 5]' | $HQ '.[] | . * 2'"

    echo "### Select"
    echo
    echo "Filter values with \`select(condition)\`:"
    echo
    run_example "echo '[1, 2, 3, 4, 5]' | $HQ '.[] | select(. > 2)'"
    run_example "echo '[{\"name\": \"Alice\", \"age\": 30}, {\"name\": \"Bob\", \"age\": 20}]' | $HQ '.[] | select(.age > 25) | .name'"

    echo "## Operators"
    echo
    echo "### Arithmetic"
    echo
    run_example "$HQ -n '2 + 3'"
    run_example "$HQ -n '10 - 4'"
    run_example "$HQ -n '6 * 7'"
    run_example "$HQ -n '20 / 4'"
    run_example "$HQ -n '17 % 5'"
    run_example "$HQ -n '2 + 3 * 4'"
    run_example "$HQ -n '(2 + 3) * 4'"

    echo "### Comparison"
    echo
    run_example "$HQ -n '5 > 3'"
    run_example "$HQ -n '5 < 3'"
    run_example "$HQ -n '5 == 5'"
    run_example "$HQ -n '5 != 3'"
    run_example "$HQ -n '5 >= 5'"
    run_example "$HQ -n '5 <= 4'"

    echo "### Boolean"
    echo
    run_example "$HQ -n 'true and false'"
    run_example "$HQ -n 'true or false'"
    run_example "$HQ -n 'true | not'"
    run_example "$HQ -n 'null | not'"

    echo "## Built-in Functions"
    echo
    echo "### Type and Length"
    echo
    run_example "echo '\"hello\"' | $HQ 'type'"
    run_example "echo '[1, 2, 3]' | $HQ 'type'"
    run_example "echo '{\"a\": 1}' | $HQ 'type'"
    run_example "echo '[1, 2, 3, 4, 5]' | $HQ 'length'"
    run_example "echo '\"hello world\"' | $HQ 'length'"

    echo "### Keys and Values"
    echo
    run_example "echo '{\"name\": \"Alice\", \"age\": 30}' | $HQ 'keys'"

    echo "### Array Functions"
    echo
    run_example "echo '[3, 1, 4, 1, 5, 9, 2, 6]' | $HQ 'sort'"
    run_example "echo '[1, 2, 2, 3, 3, 3, 4]' | $HQ 'unique'"
    run_example "echo '[1, 2, 3, 4, 5]' | $HQ 'reverse'"
    run_example "echo '[1, 2, 3, 4, 5]' | $HQ 'first'"
    run_example "echo '[1, 2, 3, 4, 5]' | $HQ 'last'"

    echo "### Add"
    echo
    run_example "echo '[1, 2, 3, 4, 5]' | $HQ 'add'"
    run_example "echo '[[1, 2], [3, 4], [5]]' | $HQ 'add'"
    run_example "echo '[\"hello\", \" \", \"world\"]' | $HQ 'add'"

    echo "### Map"
    echo
    run_example "echo '[1, 2, 3]' | $HQ 'map(. * 10)'"
    run_example "echo '[1, 2, 3, 4, 5]' | $HQ 'map(. * . )'"

    echo "### String Functions"
    echo
    run_example "echo '\"hello world\"' | $HQ 'ascii_upcase'"
    run_example "echo '\"HELLO WORLD\"' | $HQ 'ascii_downcase'"
    run_example "echo '\"hello,world,foo,bar\"' | $HQ 'split(\",\")'"
    run_example "echo '[\"hello\", \"world\"]' | $HQ 'join(\" \")'"
    run_example "echo '\"hello world\"' | $HQ 'startswith(\"hello\")'"
    run_example "echo '\"hello world\"' | $HQ 'endswith(\"world\")'"

    echo "## Variables and Binding"
    echo
    echo "### Simple Variable Binding"
    echo
    echo "Bind values to variables with \`as \$var\`:"
    echo
    run_example "echo '{\"x\": 10, \"y\": 20}' | $HQ '.x as \$a | .y as \$b | \$a + \$b'"
    run_example "echo '{\"items\": [1, 2, 3], \"multiplier\": 10}' | $HQ '.multiplier as \$m | [.items[] | . * \$m]'"

    echo "### Destructuring Bind"
    echo
    echo "Extract multiple fields at once with destructuring:"
    echo
    run_example "echo '{\"point\": {\"x\": 10, \"y\": 20}}' | $HQ '.point as {x: \$x, y: \$y} | \$x + \$y'"
    run_example "echo '{\"person\": {\"name\": \"Alice\", \"age\": 30}}' | $HQ '.person as {name: \$n, age: \$a} | \"\(\$n) is \(\$a) years old\"'"

    echo "## Reduce"
    echo
    echo "Reduce iterates over values, accumulating a result:"
    echo
    run_example "echo '[1, 2, 3, 4, 5]' | $HQ 'reduce .[] as \$x (0; . + \$x)'"
    run_example "echo '[1, 2, 3, 4, 5]' | $HQ 'reduce .[] as \$x (1; . * \$x)'"

    echo "### Building Objects with Reduce"
    echo
    run_example "echo '[{\"key\": \"a\", \"val\": 1}, {\"key\": \"b\", \"val\": 2}]' | $HQ 'reduce .[] as \$i ({}; .[\$i.key] = \$i.val)'"

    echo "## Dynamic Index Access"
    echo
    echo "Access fields dynamically using \`.[\$var]\`:"
    echo
    run_example "echo '{\"a\": 1, \"b\": 2, \"field\": \"a\"}' | $HQ '.field as \$f | .[\$f]'"

    echo "## Conditionals"
    echo
    echo "### If-Then-Else"
    echo
    run_example "echo '5' | $HQ 'if . > 3 then \"big\" else \"small\" end'"
    run_example "echo '[1, 5, 3, 8, 2]' | $HQ '[.[] | if . > 4 then \"big\" else \"small\" end]'"

    echo "## Error Handling"
    echo
    echo "### Try-Catch"
    echo
    run_example "echo '{}' | $HQ 'try .foo.bar.baz catch \"not found\"'"
    run_example "echo '5' | $HQ 'try (1 / 0) catch \"division error\"'"

    echo "### Optional Operator"
    echo
    echo "The \`?\` operator suppresses errors:"
    echo
    run_example "echo '[{\"a\": 1}, {\"b\": 2}, {\"a\": 3}]' | $HQ '[.[] | .a?]'"

    echo "### Default Values"
    echo
    echo "Use \`//\` to provide default values for null or false:"
    echo
    run_example "echo 'null' | $HQ '. // \"default\"'"
    run_example "echo '{\"name\": null}' | $HQ '.name // \"anonymous\"'"

    echo "## String Interpolation"
    echo
    echo "Embed expressions in strings with \`\\(expr)\`:"
    echo
    run_example "echo '{\"name\": \"World\"}' | $HQ '\"Hello, \(.name)!\"'"
    run_example "echo '{\"a\": 10, \"b\": 20}' | $HQ '\"\(.a) + \(.b) = \(.a + .b)\"'"

    echo "## Regex"
    echo
    echo "### Test"
    echo
    run_example "echo '\"test@example.com\"' | $HQ 'test(\"@\")'"
    run_example "echo '\"hello123\"' | $HQ 'test(\"[0-9]+\")'"

    echo "### Match"
    echo
    run_example "echo '\"test@example.com\"' | $HQ 'match(\"(.+)@(.+)\") | .captures[].string'"

    echo "### Substitution"
    echo
    run_example "echo '\"hello world\"' | $HQ 'sub(\"world\"; \"there\")'"
    run_example "echo '\"hello world world\"' | $HQ 'gsub(\"world\"; \"planet\")'"

    echo "## Recursive Descent"
    echo
    echo "The \`..\` operator recursively descends into all values:"
    echo
    run_example "echo '{\"a\": {\"b\": {\"c\": 1}}, \"d\": 2}' | $HQ '[.. | numbers]'"
    run_example "echo '{\"users\": [{\"name\": \"Alice\"}, {\"name\": \"Bob\"}]}' | $HQ '[.. | .name? // empty]'"

    echo "## Path Operations"
    echo
    echo "### Get Paths"
    echo
    run_example "echo '{\"a\": 1, \"b\": {\"c\": 2}}' | $HQ '[paths]'"
    run_example "echo '{\"a\": 1, \"b\": {\"c\": 2}}' | $HQ '[paths(scalars)]'"

    echo "### Get/Set Path"
    echo
    run_example "echo '{\"a\": {\"b\": 1}}' | $HQ 'getpath([\"a\", \"b\"])'"
    run_example "echo '{\"a\": 1}' | $HQ 'setpath([\"b\", \"c\"]; 2)'"

    echo "## Assignment Operators"
    echo
    echo "### Simple Assignment"
    echo
    run_example "echo '{\"a\": 1}' | $HQ '.b = 2'"
    run_example "echo '{\"a\": 1}' | $HQ '.a = 10'"

    echo "### Update Assignment"
    echo
    run_example "echo '{\"a\": 1}' | $HQ '.a |= . + 1'"
    run_example "echo '[1, 2, 3]' | $HQ '.[] |= . * 2'"

    echo "### Arithmetic Assignment"
    echo
    run_example "echo '{\"count\": 5}' | $HQ '.count += 1'"
    run_example "echo '{\"count\": 5}' | $HQ '.count -= 2'"
    run_example "echo '{\"count\": 5}' | $HQ '.count *= 3'"

    echo "### Delete"
    echo
    run_example "echo '{\"a\": 1, \"b\": 2, \"c\": 3}' | $HQ 'del(.b)'"

    echo "## Object Transforms"
    echo
    echo "### to_entries / from_entries"
    echo
    run_example "echo '{\"a\": 1, \"b\": 2}' | $HQ 'to_entries'"
    run_example "echo '[{\"key\": \"a\", \"value\": 1}, {\"key\": \"b\", \"value\": 2}]' | $HQ 'from_entries'"

    echo "### with_entries"
    echo
    run_example "echo '{\"a\": 1, \"b\": 2}' | $HQ 'with_entries(.value += 10)'"
    run_example "echo '{\"foo\": 1, \"bar\": 2}' | $HQ 'with_entries(.key = \"prefix_\" + .key)'"

    echo "## Output Formats"
    echo
    echo "### HUML (default)"
    echo
    run_example "echo '{\"users\": [{\"name\": \"Alice\"}, {\"name\": \"Bob\"}]}' | $HQ '.'"

    echo "### JSON"
    echo
    run_example "echo '{\"name\": \"Alice\", \"age\": 30}' | $HQ -o json '.'"

    echo "### Compact JSON"
    echo
    run_example "echo '{\"name\": \"Alice\", \"age\": 30}' | $HQ -o json -c '.'"

    echo "### YAML"
    echo
    run_example "echo '{\"name\": \"Alice\", \"age\": 30}' | $HQ -o yaml '.'"

    echo "### Raw Output"
    echo
    echo "Use \`-r\` to output strings without quotes:"
    echo
    run_example "echo '{\"name\": \"Alice\"}' | $HQ -r '.name'"

    echo "## Real-World Examples"
    echo
    echo "### Extract User Names"
    echo
    run_example "echo '{\"users\": [{\"name\": \"Alice\", \"role\": \"admin\"}, {\"name\": \"Bob\", \"role\": \"user\"}]}' | $HQ '.users[].name'"

    echo "### Filter Active Users"
    echo
    run_example "echo '[{\"name\": \"Alice\", \"active\": true}, {\"name\": \"Bob\", \"active\": false}, {\"name\": \"Carol\", \"active\": true}]' | $HQ '.[] | select(.active) | .name'"

    echo "### Transform Data"
    echo
    run_example "echo '{\"firstName\": \"Alice\", \"lastName\": \"Smith\"}' | $HQ '{name: .firstName, surname: .lastName}'"

    echo "### Calculate Statistics"
    echo
    run_example "echo '[10, 20, 30, 40, 50]' | $HQ 'add'"
    run_example "echo '[10, 20, 30, 40, 50]' | $HQ 'length'"

    echo "### Process Config Files"
    echo
    cat << 'CONFIGEXAMPLE'
```bash
# Read a HUML config and extract values
cat config.huml | hq '.database.host'

# Convert JSON config to HUML
cat config.json | hq '.' > config.huml

# Convert HUML to JSON
cat config.huml | hq -o json '.' > config.json
```
CONFIGEXAMPLE
    echo

    echo "---"
    echo
    echo "*Generated by \`scripts/generate_walkthrough.sh\` on $(date -u +"%Y-%m-%d %H:%M:%S UTC")*"

} >> "$OUTPUT"

echo "Generated $OUTPUT"
